{{- if include "server.enabled" . | eq "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server.fullname" . }}
  labels:
{{- include "server.labels" . | nindent 4 }}
spec:
{{- if not .Values.server.autoscaling.enabled }}
  replicas: {{ .Values.server.replicas }}
{{- end }}
  selector:
    matchLabels:
{{- include "server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "server.podLabels" . | nindent 8 }}
      annotations:
{{- include "server.podAnnotations" . | nindent 8 }}
    spec:
      automountServiceAccountToken: {{ .Values.server.serviceAccount.automountServiceAccountToken }}
      serviceAccountName: {{ include "server.serviceAccountName" . }}
      imagePullSecrets:
{{- include "server.imagePullSecrets" . | nindent 8 }}
      securityContext:
{{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.server.componentName }}
          securityContext:
{{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ include "server.image.repository" . }}:{{ include "server.image.tag" . }}"
          imagePullPolicy: {{ include "server.image.pullPolicy" . }}
          args:
            - server
            - -f
            - /etc/infrahq/infra.yaml
# set log level through command line parameters since its not possible to set using configuration file values
{{- with .Values.server.config.logLevel }}
            - --log-level
            - {{ . }}
{{- end }}
          env:
{{- include "server.env" . | nindent 12 }}
          envFrom:
{{- include "server.envFrom" . | nindent 12 }}
          volumeMounts:
            - name: conf
              mountPath: /etc/infrahq
              readOnly: true
{{- if (not .Values.server.config.tls) }}
            - name: tls-ca
              mountPath: /var/run/secrets/infrahq.com/tls-ca
              readOnly: true
{{- end }}
{{- if not .Values.server.config.dbEncryptionKey }}
            - name: encryption-key
              mountPath: /var/run/secrets/infrahq.com/encryption-key
              readOnly: true
{{- end }}
{{- if .Values.server.volumeMounts }}
{{- toYaml .Values.server.volumeMounts | nindent 12 }}
{{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.server.config.addr.http }}
              protocol: TCP
            - name: https
              containerPort: {{ .Values.server.config.addr.https }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.server.config.addr.metrics }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            successThreshold: {{ .Values.server.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.server.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.server.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.server.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            successThreshold: {{ .Values.server.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.server.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.server.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.server.readinessProbe.timeoutSeconds }}
          resources:
{{- toYaml .Values.server.resources | nindent 12 }}
{{- if include "postgres.enabled" . | eq "true" }}
      initContainers:
        - name: postgres-ready
          image: postgres:14-alpine
          command: [sh, -c]
          args:
            - while ! pg_isready; do sleep 0.2; done
          env:
            - name: PGHOST
              value: {{ include "postgres.fullname" . }}
            - name: PGPORT
              value: {{ .Values.postgres.service.port }}
            - name: PGDATABASE
              value: {{ .Values.postgres.dbName }}
            - name: PGUSER
              value: {{ .Values.postgres.dbUsername }}
{{- end }}
      volumes:
        - name: conf
          configMap:
            name: {{ include "server.fullname" . }}
{{- if (not .Values.server.config.tls) }}
        - name: tls-ca
          secret:
            secretName: {{ include "server.fullname" . }}-ca
{{- end }}
{{- if not .Values.server.config.dbEncryptionKey }}
        - name: encryption-key
          secret:
            secretName: {{ include "server.fullname" . }}-encryption-key
{{- end }}
{{- if .Values.server.volumes }}
{{- toYaml .Values.server.volumes | nindent 8 }}
{{- end }}
{{- with .Values.server.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.server.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.server.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- end }}
