version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: maintain
      include: scope
  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: weekly
    commit-message:
      prefix: maintain
      include: scope
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: maintain
      include: scope
