# The labels in this file will be synced to Github by the Github workflow in
# .github/workflows/manage-labels.yaml
#
# All labels are organized by category using a <category>/ prefix


- name: "kind/bug"
  color: "d73a4a"
  description: A report or a fix for a problem with functional correctness.
- name: "kind/feature"
  color: "a2eeef"
  description: A request or change that improves functional suitability.
- name: "kind/improvement"
  color: "d8d468"
  description: A report of a quality problem, or a change that addresses a quality problem.
- name: "kind/maintenance"
  color: "605f11"
  description: A change related to the maintenance of the project.
- name: "kind/question"
  color: "d876e3"
  description: A request for more information.


- name: "area/documentation"
  color: "0075ca"
  description: Improvements or additions to documentation.
- name: "area/api"
  color: "11dd3d"
  description: Issue or PR related to the Infra API.
- name: "area/ui"
  color: "0246d8"
- name: "area/deploy"
  color: "BFA38D"
  description: Issue or PR related to deploying Infra.
- name: "area/release"
  color: "fbca04"
- name: "area/cli"
  color: "ca10ac"
  description: Issue or PR related to the command-line interface.
- name: "area/destinations"
  color: "ac82da"
- name: "area/destinations/kubernetes"
  color: "e2057a"
- name: "area/providers"
  color: "71edd1"
- name: "area/providers/okta"
  color: "07269e"
- name: "area/providers/infra"
  color: "b3b781"
- name: "area/ci"
  color: "000000"
  description: Issue or PR related to Github actions, and other CI automation.
- name: "area/observability"
  color: "9ced24"
  description: Issue or PR related to observability.
- name: "area/secrets"
  color: "d5bad1"
  from_name: "secrets"


- name: "priority/high"
  color: "d93f0b"
  description: The issue is high priority.


- name: "status/idea"
  color: "ffffff"
  description: The issue is an idea that may require more research.
- name: "status/blocked"
  color: "b60205"
  description: The issue is blocked on out-of-repository dependencies.
