apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infra.fullname" . }}
  labels:
{{- include "infra.labels" . | nindent 4 }}
data:
  config.yaml: |
{{- if .Values.config.import }}
    import:
      {{- toYaml .Values.config.import | nindent 6 }}
{{- end }}
    {{- toYaml (omit .Values.config "import") | nindent 4 }}
