apiVersion: v1
kind: Secret
metadata:
  name: infra
  namespace: {{ .Release.Namespace }}
  labels:
type: Opaque
data:
  {{- if .Values.defaultApiKey }}
  default-api-key: {{ .Values.defaultApiKey | b64enc | quote }}
  {{- else }}
  default-api-key: {{ include "infra.defaultApiKey" . | b64enc | quote }}
  {{- end }}
