{{- if include "postgres.enabled" . | eq "true" }}
{{- if .Values.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
{{- include "postgres.labels" . | nindent 4 }}
{{- if .Values.postgres.persistence.labels }}
{{- toYaml .Values.postgres.persistence.labels | nindent 4 }}
{{- end }}
  annotations:
{{- toYaml .Values.postgres.persistence.annotations | nindent 4 }}
spec:
{{- if .Values.postgres.persistence.className }}
  storageClassName: {{ .Values.postgres.persistence.className | quote }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
{{- toYaml .Values.postgres.persistence.resources | nindent 6 }}
{{- end }}
{{- end }}
