{{- if include "postgres.enabled" . | eq "true" }}
{{- if not .Values.postgres.dbPasswordSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
{{- include "postgres.labels" . | nindent 4 }}
data:
{{- $secret := lookup "v1" "Secret" .Release.Namespace (include "postgres.fullname" .) }}
{{- if $secret.data }}
  password: {{ $secret.data.password }}
{{- else }}
  password: {{ randAlphaNum 16 | b64enc }}
{{- end }}
{{- end }}
{{- end }}
