apiVersion: v1
kind: Secret
metadata:
  name: infra-engine
  namespace: {{ .Release.Namespace }}
  labels:
type: Opaque
data:
  {{- if .Values.apiKey }}
  api-key: {{ .Values.apiKey | b64enc | quote }}
  {{- else }}
  api-key: {{ include "infra.defaultApiKey" . | b64enc | quote }}
  {{- end }}