name: deploy

on:
  workflow_run:
    workflows:
      - cd / ui
      - cd / core
    types:
      - completed
    branches:
      - main
  workflow_dispatch:
    inputs:
      component-name:
        type: string
        default: core
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    outputs:
      component-name: ${{ steps.component-name.outputs.component-name }}
    steps:
      - id: component-name
        run: |
          COMPONENT_NAME=$(echo ${{ github.event_name == 'workflow_run' && github.event.workflow_run.name || inputs.component-name }} | awk '{ print $NF }' )
          if [ -z "$COMPONENT_NAME" ]; then
            echo Missing Infra component name.
            exit 1
          fi

          echo "::set-output name=component-name::$COMPONENT_NAME"

  synchronize:
    runs-on: ubuntu-latest
    needs: [prepare]
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        environment:
          - name: Development
          - name: Production
    environment: ${{ matrix.environment.name }}
    concurrency:
      group: ${{ github.workflow }}-synchronize-${{ matrix.environment.name }}-${{ needs.prepare.outputs.component-name }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-infra
        with:
          infra-server: ${{ secrets.INFRA_SERVER }}
          infra-access-key: ${{ secrets.INFRA_ACCESS_KEY }}
          infra-destination: ${{ secrets.INFRA_DESTINATION }}
      - uses: ./.github/actions/setup-argocd
        with:
          argocd-tools: |
            argocd-image-updater
      - run: |
          echo Syncing Infra component-name ${{ needs.prepare.outputs.component-name }}
          argocd-image-updater run --once --match-application-label=app.infrahq.com/component=${{ needs.prepare.outputs.component-name }}
