name: pull request

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - run: go install gotest.tools/gotestsum@v1.8.0
      - run: go mod tidy
      - run: ~/go/bin/gotestsum -ftestname -- -race ./...
      - name: Check that tests leave a clean git checkout
        run: |
          # show and check changes to committed files
          git diff --exit-code
          # show and check for uncommitted files
          git status --short; [[ "$(git status --short)" == "" ]]

  test-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - working-directory: ui
        run: |
          npm install
          npm test

  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - uses: golangci/golangci-lint-action@v3.2.0

  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Azure/setup-helm@v1
      - run: make helm/lint tag=0.0.0-development

  check-generated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Check generated docs are updated
        run: |
          # if checking a release candidate pull request, unset `internal.Metadata`
          if [[ "$GITHUB_HEAD_REF" =~ ^release-please-.*$ ]]; then LDFLAGS='-X github.com/infrahq/infra/internal.Metadata='; fi
          # fake a terminal to get the right defaults for non-interactive
          script -e -q -c "go run ${LDFLAGS:+-ldflags \"$LDFLAGS\"} ./internal/docgen"
          go run ${LDFLAGS:+-ldflags "$LDFLAGS"} ./internal/openapigen docs/api/openapi3.json
          git diff --exit-code
      - name: Check go mod is tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Check generated code is updated
        run: |
          go generate ./...
          git diff --exit-code
