name: pull request

on:
  pull_request:
    branches:
      - 'release-please-*'

jobs:
  codeql-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - uses: github/codeql-action/init@v2
        with:
          config-file: .github/codeql-config.yaml
      - run: go build github.com/$GITHUB_REPOSITORY
      - uses: github/codeql-action/analyze@v2
