name: Close stale issues and pull requests

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: |
            This issue has not seen any activity in a while. Add a comment if this issue is still relevant,
            otherwise it will be closed in 7 days.
          stale-pr-message: |
            This pull request has not seen any activity in a while. Add a comment if this pull request is
            relevant, otherwise it will be closed in 14 days.
          close-issue-message: |
            This issue was closed because it is inactive.
          close-pr-message: |
            This pull request was closed because it is inactive.
          days-before-issue-stale: 60
          days-before-issue-close: 7
          days-before-pr-stale: 90
          days-before-pr-close: 14
          exempt-all-pr-assignees: true
          stale-issue-label: status/stale
          stale-pr-label: status/stale
          exempt-issue-labels: status/never-stale
          exempt-pr-labels: status/never-stale
